import lamini
from dotenv import load_dotenv
import os
from lamini import LaminiClassifier

load_dotenv()
lamini.api_key = os.getenv("API_KEY")

classifier = LaminiClassifier()

prompts = {
            "ACÓRDÃO":
            ["Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da CORTE ESPECIAL do Superior\nTribunal de Justiça, em sessão virtual de 18/05/2022 a 24/05/2022,\npor unanimidade, negar provimento ao recurso, nos termos do voto do\nSr. Ministro Relator.\nOs Srs. Ministros Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha, Maria Thereza de Assis Moura, Herman Benjamin, Jorge Mussi,\nOg Fernandes, Luis Felipe Salomão, Mauro Campbell Marques, Raul\nAraújo, Paulo de Tarso Sanseverino e Maria Isabel Gallotti  votaram\ncom o Sr. Ministro Relator.\nNão participou do julgamento o Sr. Ministro Benedito Gonçalves.\nPresidiu o julgamento o Sr. Ministro Humberto Martins.Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da CORTE ESPECIAL do Superior\nTribunal de Justiça, em sessão virtual de 18/05/2022 a 24/05/2022,\npor unanimidade, negar provimento ao recurso, nos termos do voto do\nSr. Ministro Relator.\nOs Srs. Ministros Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha, Maria Thereza de Assis Moura, Herman Benjamin, Jorge Mussi,\nOg Fernandes, Luis Felipe Salomão, Mauro Campbell Marques, Raul\nAraújo, Paulo de Tarso Sanseverino e Maria Isabel Gallotti  votaram\ncom o Sr. Ministro Relator.\nNão participou do julgamento o Sr. Ministro Benedito Gonçalves.\nPresidiu o julgamento o Sr. Ministro Humberto Martins.", 
             "Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da Corte Especial, por unanimidade,\nacolher os embargos de declaração, com efeitos modificativos, nos\ntermos do voto do Sr. Ministro Relator.\nOs Srs. Ministros Og Fernandes, Luis Felipe Salomão, Mauro Campbell\nMarques, Benedito Gonçalves, Raul Araújo, Maria Isabel Gallotti,\nFrancisco Falcão, Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha e Maria Thereza de Assis Moura votaram com o Sr. Ministro\nRelator.\nAusentes, justificadamente, os Srs. Ministros Herman Benjamin e\nPaulo de Tarso Sanseverino.\nLicenciado o Sr. Ministro Felix Fischer."]
           }

classifier.prompt_train(prompts)


print(classifier.predict(["Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da CORTE ESPECIAL do Superior\nTribunal de Justiça, em sessão virtual de 18/05/2022 a 24/05/2022,\npor unanimidade, negar provimento ao recurso, nos termos do voto do\nSr. Ministro Relator.\nOs Srs. Ministros Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha, Maria Thereza de Assis Moura, Herman Benjamin, Jorge Mussi,\nOg Fernandes, Luis Felipe Salomão, Mauro Campbell Marques, Raul\nAraújo, Paulo de Tarso Sanseverino e Maria Isabel Gallotti  votaram\ncom o Sr. Ministro Relator.\nNão participou do julgamento o Sr. Ministro Benedito Gonçalves.\nPresidiu o julgamento o Sr. Ministro Humberto Martins.Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da CORTE ESPECIAL do Superior\nTribunal de Justiça, em sessão virtual de 18/05/2022 a 24/05/2022,\npor unanimidade, negar provimento ao recurso, nos termos do voto do\nSr. Ministro Relator.\nOs Srs. Ministros Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha, Maria Thereza de Assis Moura, Herman Benjamin, Jorge Mussi,\nOg Fernandes, Luis Felipe Salomão, Mauro Campbell Marques, Raul\nAraújo, Paulo de Tarso Sanseverino e Maria Isabel Gallotti  votaram\ncom o Sr. Ministro Relator.\nNão participou do julgamento o Sr. Ministro Benedito Gonçalves.\nPresidiu o julgamento o Sr. Ministro Humberto Martins.","Vistos e relatados estes autos em que são partes as acima\nindicadas, acordam os Ministros da Corte Especial, por unanimidade,\nacolher os embargos de declaração, com efeitos modificativos, nos\ntermos do voto do Sr. Ministro Relator.\nOs Srs. Ministros Og Fernandes, Luis Felipe Salomão, Mauro Campbell\nMarques, Benedito Gonçalves, Raul Araújo, Maria Isabel Gallotti,\nFrancisco Falcão, Nancy Andrighi, Laurita Vaz, João Otávio de\nNoronha e Maria Thereza de Assis Moura votaram com o Sr. Ministro\nRelator.\nAusentes, justificadamente, os Srs. Ministros Herman Benjamin e\nPaulo de Tarso Sanseverino.\nLicenciado o Sr. Ministro Felix Fischer."]))